# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: parsing/foo.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()

DESCRIPTOR = _descriptor.FileDescriptor(
    name='parsing/foo.proto',
    package='example',
    syntax='proto2',
    serialized_pb=b'\n\x11parsing/foo.proto\x12\x07\x65xample\"$\n\x05Thing\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x03(\x02\")\n\x07\x41\x64\x64ress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\x05\"Y\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12!\n\x07\x61\x64\x64ress\x18\x02 \x01(\x0b\x32\x10.example.Address\x12\x1e\n\x06things\x18\x03 \x03(\x0b\x32\x0e.example.Thing')
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_THING = _descriptor.Descriptor(
    name='Thing',
    full_name='example.Thing',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.Thing.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='value', full_name='example.Thing.value', index=1,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=30,
    serialized_end=66,
)


_ADDRESS = _descriptor.Descriptor(
    name='Address',
    full_name='example.Address',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    _descriptor.FieldDescriptor(
      name='street', full_name='example.Address.street', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number', full_name='example.Address.number', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=68,
    serialized_end=109,
)


_PERSON = _descriptor.Descriptor(
    name='Person',
    full_name='example.Person',
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='example.Person.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='address', full_name='example.Person.address', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='things', full_name='example.Person.things', index=2,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    ],
    extensions=[
    ],
    nested_types=[],
    enum_types=[
    ],
    options=None,
    is_extendable=False,
    syntax='proto2',
    extension_ranges=[],
    oneofs=[
    ],
    serialized_start=111,
    serialized_end=200,
)

_PERSON.fields_by_name['address'].message_type = _ADDRESS
_PERSON.fields_by_name['things'].message_type = _THING
DESCRIPTOR.message_types_by_name['Thing'] = _THING
DESCRIPTOR.message_types_by_name['Address'] = _ADDRESS
DESCRIPTOR.message_types_by_name['Person'] = _PERSON

Thing = _reflection.GeneratedProtocolMessageType(
    'Thing',
    (_message.Message, ),
    dict(DESCRIPTOR=_THING,
         __module__='parsing.foo_pb2'
         # @@protoc_insertion_point(class_scope:example.Thing)
         ))
_sym_db.RegisterMessage(Thing)

Address = _reflection.GeneratedProtocolMessageType(
    'Address',
    (_message.Message, ),
    dict(DESCRIPTOR=_ADDRESS,
         __module__='parsing.foo_pb2'
         # @@protoc_insertion_point(class_scope:example.Address)
         ))
_sym_db.RegisterMessage(Address)

Person = _reflection.GeneratedProtocolMessageType(
    'Person',
    (_message.Message, ),
    dict(DESCRIPTOR=_PERSON,
         __module__='parsing.foo_pb2'
         # @@protoc_insertion_point(class_scope:example.Person)
         ))
_sym_db.RegisterMessage(Person)

# @@protoc_insertion_point(module_scope)
